site_name: ΩMEGA
site_url: https://FrankSchumann.github.io/omega/
repo_url: https://github.com/FrankSchumann/omega/
copyright: Frank Schumann
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime
markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed
  - toc:
      permalink: true
plugins:
  - search
nav:
  - Home: 'index.md'
  - Systemkontext: 'systemkontext.md'
  - Bausteinsicht: 'bausteinsicht.md'
