site_name: OMEGA
site_url: https://pages.github.schneider-electric.com/MSol-NGM-HPC/hpc-handbook/
repo_url: https://github.schneider-electric.com/MSol-NGM-HPC/hpc-handbook/
copyright: Frank Schumann
extra_css:
  - schneider.css
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.top
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed
  - toc:
      permalink: true
plugins:
  - search
nav:
  - Home: 'index.md'
  - Systemkontext:
  - Bausteinsicht:
  - Test1: 
    - Overview: 'Onboarding/index.md'
    - Useful Links: 'Onboarding/useful_links.md'
    - Todo List for the new colleagues: 'Onboarding/todo_list_newcomers.md'
